### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by SamKr** [Rafaeruo/pkl-csharp#15]
This is looking great, thanks for your work. As the title says 'still a WIP', would you say it's ready for production? And since the last commit has been a few months, are you still actively working on it?

**Comment by jeremyvaartjes** [comment]
I can't speak for @Rafaeruo as to what he intends but I still have intention of keeping this one going, just been a little busy 😅. I'll put a list of issues together on things that still need to be done to be considered "1.0".
But in this project's current state, it could technically be used if all you care about is reading files in dynamically. Non of the code gen stuff is ready but if you have the types used in your pkl files hardcoded in your c# files then you can just typecast against those.

**Comment by jeremyvaartjes** [comment]
I just uploaded a nuget package for what's currently in our repo to nuget.org if you wanted to play with it. I'd say until it's in a better state it's not "production" ready, but usable.

https://www.nuget.org/packages/PklCsharp/

**Comment by SamKr** [comment]
Perfect, thanks! I'll start playing with it. Reading files is pretty much what I'm looking for at this point :) Cheers
